name: Upload to S3
on:
    push:
        branches:
            - main
jobs:
    Upload-to-S3:
        runs-on: macos-lastest
        steps:
            - uses: actions/checkout@v2
            - name: Check
              run: |
                    echo "Checking"
            
